DELETE http://localhost:3003/api/blogs/234234
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcnVtYW4iLCJpZCI6IjY0ZTlkN2NiY2NmZmY5OGU4MjQ5MDRhZiIsImlhdCI6MTY5MzEzMTg2NSwiZXhwIjoxNjkzMTM1NDY1fQ.ajQcsf9EXR9iKWn09bVm3uFnQIoamAneOLomxFpLDmE
