DELETE http://localhost:3003/api/blogs/64eb1d307b659e99dbba3222
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhcnVtYW4iLCJpZCI6IjY0ZTlkN2NiY2NmZmY5OGU4MjQ5MDRhZiIsImlhdCI6MTY5MzEzMDQzNiwiZXhwIjoxNjkzMTM0MDM2fQ.inkzz61oUBhxX9RWZ1drk1Hvd5nRWBLeR1BfPYVPrNw
